version: "2"

services:
  uio:
    image: harbor.uio.no/usit-int/cerebrum_uio:latest
    volumes:
      - .:/src:z
    networks:
      - cerebrum
    working_dir: /src/testsuite/docker
    depends_on:
      - db
    environment:
      - DOCKER_ROOT_DIR=/src/testsuite/docker
      - TEST_CONFIG_DIR=/src/testsuite/docker/test-config
      - CEREBRUM_CONFIG_DIR=/src/testsuite/docker/cerebrum_config
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - INST=uio
      - DB_NAME=cerebrum_uio
    command: /src/testsuite/docker/generate-test-reports.sh

  db:
    image: harbor.uio.no/library/postgres:latest
    networks:
      - cerebrum

networks:
  cerebrum:
    driver: bridge