# Set up Cerebrum
#
# - install Cerebrum
#

# TDB: Should we use `pip install --upgrade`?
- name: install cerebrum
  action: command {{ virtualenv }}/bin/python setup.py install --prefix={{ virtualenv }}
          chdir={{ crb_src_dir }}

- name: locate virtualenv site-packages
  virtualenv_info:
      env: "{{ virtualenv }}"
      info: site
  register: _virtualenv_info
