# Cerebrum role

- debug: var={{ item }}
  when: debug is defined
  with_items:
      - virtualenv
      - crb_src_dir
      - pip_offline
      - pip_local
      - pip_proxy
      - pip_cache
  tags:
    - always

- include: setup_host.yml
  tags:
    - host

- include: setup_virtualenv.yml
  tags:
    - env

